# Data Structures

## Article Base (object)
+ object: `article` (string)
+ id (string)
+ title (string)
+ favicon (string)
+ link (string) - URL of the article
+ created_at (string) - ISODate

## Article (Article Base)

## Articles (array[Article])