# Data Structures

## GeoJSON Point (object)
+ type: Point (string)
+ coordinates: 40.703908, 74.011390 (array)

## GeoJSON Polygon (object)
+ type: Polygon (string)
+ coordinates (array)
    + (array)
        + ([GeoJSON Coordinate][])
        + ([GeoJSON Coordinate][])
        + ([GeoJSON Coordinate][])

## GeoJSON MultiPoint (object)
+ type: MultiPoint (string)
+ coordinates (array)
    + ([GeoJSON Coordinate][])
    + ([GeoJSON Coordinate][])

## GeoJSON Coordinate (array)
+ `40.703908` (number)
+ `-74.011390` (number)