# Data Structures

## Search Results (object)
+ posts
    + count: 1 (number) - Number of total results that match model search in Fresco (not in result)
    + results ([Posts][]) - Array of post results
+ galleries
    + count: 1 (number) - Number of total results that match model search in Fresco (not in result)
    + results ([Galleries][]) - Array of gallery results
+ assignments
    + count: 1 (number) - Number of total results that match model search in Fresco (not in result)
    + results ([Assignments][]) - Array of assignment results
+ users
    + count: 1 (number) - Number of total results that match model search in Fresco (not in result)
    + results ([Users][]) - Array of user results
+ outlets
    + count: 1 (number) - Number of total results that match model search in Fresco (not in result)
    + results ([Outlets][]) - Array of post results