CREATE TABLE outlet_payment (
    id BIGSERIAL PRIMARY KEY,
    outlet_id BIGINT NOT NULL,
    stripe_source_id TEXT DEFAULT NULL,
    type CHARACTER VARYING(16) DEFAULT NULL, -- TODO ?????
    brand CHARACTER VARYING(24) DEFAULT NULL,
    last4 CHARACTER VARYING(4) DEFAULT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    valid BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);