CREATE TABLE user_payment (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    stripe_id TEXT DEFAULT NULL,
    type CHARACTER VARYING(16) DEFAULT NULL,
    brand CHARACTER VARYING(48) DEFAULT NULL,
    last4 CHARACTER VARYING(4) DEFAULT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    valid BOOLEAN NOT NULL DEFAULT TRUE,
    never_used BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);