CREATE TABLE articles (
    __mongo_id CHARACTER(24) DEFAULT NULL,
    __mongo_outlet_title TEXT DEFAULT NULL,

    id BIGSERIAL PRIMARY KEY,
    title TEXT,
    outlet_id BIGINT DEFAULT NULL,
    link CHARACTER VARYING(256) DEFAULT NULL,
    favicon CHARACTER VARYING(256) DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    _fts TSVECTOR DEFAULT NULL
);
