\i ./triggers/articles.sql
\i ./triggers/assignments.sql
\i ./triggers/galleries.sql
\i ./triggers/gallery_posts.sql
\i ./triggers/installations.sql
\i ./triggers/outlet_payment.sql
\i ./triggers/outlets.sql
\i ./triggers/posts.sql
\i ./triggers/stories.sql
\i ./triggers/story_galleries.sql
\i ./triggers/user_payment.sql
\i ./triggers/users.sql