\i ./constraints/articles.sql
\i ./constraints/assignment_outlets.sql
\i ./constraints/assignment_users.sql
\i ./constraints/assignments.sql
\i ./constraints/comment_entities.sql
\i ./constraints/comments.sql
\i ./constraints/following_users.sql
\i ./constraints/galleries.sql
\i ./constraints/gallery_articles.sql
\i ./constraints/gallery_comments.sql
\i ./constraints/gallery_likes.sql
\i ./constraints/gallery_posts.sql
\i ./constraints/gallery_reports.sql
\i ./constraints/gallery_reposts.sql
\i ./constraints/installation_subscriptions.sql
\i ./constraints/installations.sql
\i ./constraints/notification_users.sql
\i ./constraints/notifications.sql
\i ./constraints/oauth_access_tokens.sql
\i ./constraints/oauth_authorization_codes.sql
\i ./constraints/oauth_client_families.sql
\i ./constraints/oauth_clients.sql
\i ./constraints/outlet_invites.sql
\i ./constraints/outlet_location_notification_settings.sql
\i ./constraints/outlet_locations.sql
\i ./constraints/outlet_payment.sql
\i ./constraints/outlets.sql
\i ./constraints/posts.sql
\i ./constraints/purchases.sql
\i ./constraints/recap_stories.sql
\i ./constraints/reports.sql
\i ./constraints/social_links.sql
\i ./constraints/stories.sql
\i ./constraints/story_articles.sql
\i ./constraints/story_comments.sql
\i ./constraints/story_galleries.sql
\i ./constraints/story_likes.sql
\i ./constraints/story_reposts.sql
\i ./constraints/user_blocks.sql
\i ./constraints/user_identites.sql
\i ./constraints/user_identites.sql
\i ./constraints/user_locations.sql
\i ./constraints/user_payment.sql
\i ./constraints/user_reports.sql
\i ./constraints/user_settings.sql
\i ./constraints/users.sql
